services:
  backend:
    build: ./backend
    container_name: ujr_backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/mock_db.json:/app/mock_db.json
    restart: always

  frontend:
    build: ./frontend
    container_name: ujr_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
